---
- hosts: borg
  remote_user: root
  tasks:
     
    - name: Upgrade all packages to the latest version
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Installs necessary packages
      apt:
       name: "{{ packages }}"
      vars:
       packages:
               - python3
               - python3-dev
               - python3-pip
               - python-virtualenv
               - libssl-dev
               - openssl
               - libacl1-dev
               - libacl1
               - build-essential
               - libfuse-dev
               - fuse
               - pkg-config

    - name: create symlink pip to pip3
      raw: ln -s /usr/bin/pip3 /usr/bin/pip

    - name: Install Borg from PIP
      pip:
       name: borgbackup[fuse]

...
# vim:ft=ansible:
